services:
  - type: web
    name: bitespeed-identity
    env: node
    nodeVersion: 18
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
